---
title: Here I go
author: Fousseynou Bah
date: '2018-05-02'
slug: here-i-go
categories:
  - R
tags:
  - R Markdown
---


I'm terrified as I write these words.
Not because I've been summoned by Queen Cersei or because I'm fighting the White Walkers alongside Jon Snow.
No.
I wish I was though. 
Ok, almost.
I'm terrified because this is my first step in blogging.
Few years back, when I was younger, I probably would've been fine.
But now, now that I know how much words matter, I tend to be cautious when talking or writing.
Once it's out there, it is out there.
But that's no excuse.

Few months back, I decided to test the waters with R.
So far, I had been using Stata.
We had a steady relationship, but somewhere along the way we started to grow apart.
Stata had newer, stronger, better versions released while I kept using the one I acquired during my graduate studies (late 2000's!).
In truth, I stayed behind.
Well, not entirely.
I started to feel strongly about "open-source".
Between my first encounter with Stata and our break-up, I came to discover the joys (and sometimes the tribulations) of open-source programs and systems.
My heart keeps beating for Ubuntu, but for practicals reasons (working in a Windows-dominated environment), I have to postpone our reunion.
We'll be together one day.
One sweet day (a great song, by the way).
I also enjoyed my time QGIS.
For some time, it made feel like a God, a God of Maps.
But outside the projects where I needed maps, we didn't hang out very much (after all, that's all it can do).
And also, I found it hard to navigate between different programs (Stata there, QGIS here, a database there,...).
With time, the distance between us grew wider.
One thing though. 
I'm to blame, partially.
I didn't bother to master SQL to skip the middle man (in this case, Stata), to access directly my databases from QGIS.
Anyway...water under the bridge.

My relationships with those tools had their on-and-off moments (like Ross and Rachel).
Sure, I had my share of sleepness nights trying to figure out why my system was behaving strangely, or trying take over a document created by a colleague under another system and with another program (imagine MS Office versus LibreOffice).
But, overall, I got a glimpse of the possibilities that lie ahead.
With the release of new versions on regular basis, the pace at which bugs are addressed, it seems like open-source stands and will remain among and the forces the technological innovations (Thomas Friedman of New York times writes about those things so eloquently. More than I ever could. Go read him!).
And also, many of those programs and systems are free!
And that is a practical reason that trumps all the other practical reasons.

Back to R.
Last year, I had a moment of...epiphany.
Considering all the history I shared with Stata, the flings I had with Ubuntu and QGIS, and the better tomorrow I see in open-source (Ok, the *free* part play a major role, I admit it), I decided to take a leap, to switch to R.
That meant rewriting countless lines of codes, scripts it's taken me years to write.
But, most importantly, it meant learning a new language and understanding a new environment.
I went online to get some tutorials.
I got many for free, but I didn't have a structure, a methology to ease my way into R and work my way up.
Then, I found DataCamp.
I tried it, liked it and kept it.
In few months I went trough a huge track, `Data Science with R`.
I took a break for few weeks, and started another one `Quantitative Analyst with R`.
I'm still on it.
Every once in while, I try some other courses outside my track just for the fun of it.

The whole experience has been eye-opening.
All I can think to myself is why I didn't switch sooner.
In fact, I could've because I had courses on R during my undergraduate studies.
I didn't bother to go because, well, I didn't think skipping them would hurt my grades (it did!), or that in the future I would work as data analyst (as opposed the great *Professor of Internal Economics* I though I would become).
Hey, better late than never. 
Right?
I found in R a place I think I want to call home for a very, very long time.
And, in all honesty, RStudio has a lot to do with it (I'm not being paid by RStudio to say that!).
I get to stay in one place and do a lot, from writing my scripts (I'm still *translating* the codes I wrote in my Stata days), to creating amazing graphs and maps with *ggplot2* (sorry QGIS, R really does all I need), to writing reports or articles with Latex.
And that's wonderful.

And now, this blog.
My switch to R came along with (or went from) the desire to be a part of what makes this time in history particular (well, in my humble opinion).
And that is how the computerization of our lives is, at the same time, fueling and feeding off of technological advancement.
Think how phones have gotten smaller and smaller all the while getting smarter and smarter, capable of collecting more data than ever about every aspect of our daily routines.
Think how the avalability of data (thanks to increasingly powerful computers) is enabling machines to learn faster and do better what they're designed to do (read Thomas Friedman. Seriously!).
Sure, with the hype around data science, machine learning and artificial intelligence, it makes no doubt that knowing one's way around data can prove useful (personally and professionally).
But, we can go deeper than that.
We have an unprecedented opportunity to connect, to share experiences.
I'm not talking about posting on Facebook the picture of newborn daughter or the video a puppy dancing to a song.
That's fun, though.
I'm talking about how an individual project can turn into a collective one (think GitHub and, by the way, they didn't pay to say that), about how we are all better off in the face of bugs because there are forums where problems are shared and solutions are found through collaboration and interaction.

I am an African, born, raised and living in Africa.
Being from that part of world - with all the preconceved notions that come with "Africa" (and some, unfortunately, justified) -, and being a part of globalized and increasingly computerized world - where standing on the sideline in not a choice, but a sentence -, I fought my fear of words (I still haven't overcome them) and decided to start this blog.
I have been fortunate to be a part of various projects, in various sectors and places.
And, sometimes, I've been foolish enough to start few of my own.
And, with the return of R into my life, the epiphany, I saw an opportunity to dust off the few materials I have and, hopefully, find new ones.